version: '3.8'

services:
  frontend:
    build: ./material-applications/example-frontend
    ports:
      - 3000:5000
    depends_on:
      - backend

  backend:
    build: ./material-applications/example-backend
    ports:
      - 3001:8080
