version: '3.8'

services:
  frontend:
    build: ./material-applications/example-frontend
    ports:
      - 3000:5000
    depends_on:
      - backend

  backend:
    build: ./material-applications/example-backend
    ports:
      - 3001:8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
